Обновлен объект игрока и гильдии в ответах
VimeWorld/api-docs pull request #9
Opened 2021-01-30 22:10 UTC by Erelima

2021-01-30 23:17 UTC, xtrafrancyz requested changes
Спасибо за работу, но не хватает запятой

2021-01-30 23:17 UTC, xtrafrancyz commented on docs/_api/guild_search_get.md
>        "levelPercentage": 0.62691
```suggestion
      "levelPercentage": 0.62691,
```

2021-01-31 08:03 UTC, Erelima commented
Видимо ночью писать было плохой затеей

2021-01-31 09:19 UTC, xtrafrancyz approved these changes

2021-01-31 09:20 UTC, merged